runner:
    lr: 5e-4
    optim: LAMB
    train_batch_size: 256
    valid_batch_size: 256
    shuffle: False
    multi_gpu: False
    device: cuda
    total_steps: 500000
    num_workers: 16
    log_step: 1000
    checkpoint_step: 1000
    grad_clip: 1.0
    output_tb: True
    #start_from_ckpt: ???
    scheduler:
        name: ramp_up
        total_steps: ${exp.runner.total_steps}
        warmup: 0.025
        gamma: 0.99
